// ============================================================
//  download.js — Itinerary export (PDF + clipboard)
// ============================================================

export function generateTextItinerary(itinerary, locations, startDate, endDate) {
    const lines = [];
    const locStr = locations.map(l => `📍 ${l}`).join(' · ');

    lines.push(`🗺️  AI TRIP ITINERARY ✨`);
    lines.push(`📅 Dates: ${formatDateRange(startDate, endDate)}`);
    lines.push(`📍 Locations: ${locations.join(', ')}`);
    lines.push('─'.repeat(50));
    lines.push('');

    if (itinerary.summary) {
        lines.push(`💡 ${itinerary.summary}`);
        lines.push('');
    }

    const dayEmojis = ['🟦', '🟪', '🟨', '🟧', '🟥', '🟩', '🔵', '🔴', '🟤', '⚫'];

    itinerary.days.forEach((day, idx) => {
        const emoji = dayEmojis[idx % dayEmojis.length];
        lines.push(`${emoji} DAY ${day.day} — ${day.theme?.toUpperCase() || ''} 🌟`);
        lines.push(`🗓️  ${day.date}${day.location ? ' · ' + day.location : ''}`);
        lines.push('');

        day.places.forEach((place, pIdx) => {
            lines.push(`  ${pIdx + 1}. 📌 ${place.name}`);
            if (place.desc) {
                lines.push(`     ${place.desc.slice(0, 120)}${place.desc.length > 120 ? '...' : ''}`);
            }
            if (place.openingHours || place.entryFee) {
                const info = [];
                if (place.openingHours) info.push(`⏰ ${place.openingHours}`);
                if (place.entryFee) info.push(`💰 ${place.entryFee}`);
                lines.push(`     ${info.join(' | ')}`);
            }
            if (place.commute_from_prev && pIdx > 0) {
                const c = place.commute_from_prev;
                const commutes = [];
                if (c.walk && c.walk !== 'N/A') commutes.push(`🚶 ${c.walk}`);
                if (c.cab && c.cab !== 'N/A') commutes.push(`🚕 Cab: ${c.cab}`);
                if (c.metro && c.metro !== 'N/A') commutes.push(`🚇 ${c.metro}`);
                if (commutes.length) {
                    lines.push(`     ↳ From prev: ${commutes.join(' | ')}`);
                }
            }
            lines.push('');
        });
        lines.push('─'.repeat(50));
        lines.push('');
    });

    lines.push('Generated by AI Trip Planner ✈️');
    return lines.join('\n');
}

export function downloadAsText(itinerary, locations, startDate, endDate) {
    const text = generateTextItinerary(itinerary, locations, startDate, endDate);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `trip-itinerary-${startDate}-to-${endDate}.txt`;
    a.click();
    URL.revokeObjectURL(url);
}

export async function downloadAsPDF(itinerary, locations, startDate, endDate) {
    // Load jsPDF from CDN if not already loaded
    if (!window.jspdf) {
        await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');
    }
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const text = generateTextItinerary(itinerary, locations, startDate, endDate);
    const margin = 15;
    const pageW = doc.internal.pageSize.getWidth() - margin * 2;
    const lines = doc.splitTextToSize(text.replace(/[^\x00-\x7F]/g, (c) => emojiToText(c)), pageW);

    let y = margin;
    const lineH = 5;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    lines.forEach(line => {
        if (y + lineH > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
        }
        doc.text(line, margin, y);
        y += lineH;
    });

    doc.save(`trip-itinerary-${startDate}-to-${endDate}.pdf`);
}

export async function copyToClipboard(itinerary, locations, startDate, endDate) {
    const text = generateTextItinerary(itinerary, locations, startDate, endDate);
    await navigator.clipboard.writeText(text);
}

function loadScript(src) {
    return new Promise((resolve, reject) => {
        const s = document.createElement('script');
        s.src = src;
        s.onload = resolve;
        s.onerror = reject;
        document.head.appendChild(s);
    });
}

function formatDateRange(start, end) {
    const opts = { day: 'numeric', month: 'long', year: 'numeric' };
    return `${new Date(start).toLocaleDateString('en-IN', opts)} – ${new Date(end).toLocaleDateString('en-IN', opts)}`;
}

function emojiToText(char) {
    // strip emoji that jsPDF can't render — they've already appeared as beautiful text above
    return '';
}
