// ============================================================
//  build-env.js — Generates js/app-config.js at build time
//  Run by Netlify during build: `node build-env.js`
//
//  SECURITY: this file must NEVER write secrets into the publish
//  directory. Everything under `publish = "."` is served publicly,
//  so anything written here is downloadable by anyone.
//  Only non-secret capability flags are emitted; the actual API keys
//  stay in the Netlify environment and are used exclusively by the
//  serverless functions in netlify/functions/.
// ============================================================

const fs = require('fs');

const geminiKey = process.env.GEMINI_API_KEY || '';
const groqKey = process.env.GROQ_API_KEY || '';
const openrouterKey = process.env.OPENROUTER_API_KEY || '';
const unsplashKey = process.env.UNSPLASH_ACCESS_KEY || '';
const weatherKey = process.env.OPENWEATHER_API_KEY || '';

const config = {
    hasAI: Boolean(geminiKey || groqKey || openrouterKey),
    hasImages: Boolean(unsplashKey),
    hasWeather: Boolean(weatherKey),
    builtAt: new Date().toISOString(),
};

const content = `// Auto-generated by build-env.js at build time — DO NOT EDIT.
// Contains capability flags only. No secrets are ever written here.
export const APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync('js/app-config.js', content, 'utf8');

// Belt-and-braces: if an older deploy left a key-bearing env.js behind in the
// build cache, overwrite it with the safe placeholder version.
const safeEnv = `// Local development only. Real keys belong in js/env.local.js (git-ignored).
// This file is regenerated on every deploy and must never contain secrets.
export const ENV_KEYS = {};
`;
fs.writeFileSync('js/env.js', safeEnv, 'utf8');

console.log('✅ js/app-config.js generated (no secrets)');
console.log(`   • AI providers configured: ${config.hasAI}`);
console.log(`   • Unsplash configured:     ${config.hasImages}`);
console.log(`   • Weather configured:      ${config.hasWeather}`);
if (!config.hasAI) console.log('   ⚠️  No AI keys found — trip planning will not work');
if (!config.hasImages) console.log('   ⚠️  UNSPLASH_ACCESS_KEY missing — place images will use fallbacks');
if (!config.hasWeather) console.log('   ⚠️  OPENWEATHER_API_KEY missing — weather badges disabled');
