// ============================================================
//  build-env.js — Injects environment variables at build time
//  Run by Netlify during build: `node build-env.js`
// ============================================================

const fs = require('fs');

const geminiKey = process.env.GEMINI_API_KEY || '';
const groqKey = process.env.GROQ_API_KEY || '';

const content = `// Auto-generated by build-env.js — DO NOT EDIT
export const ENV_KEYS = {
  geminiKey: "${geminiKey}",
  groqKey: "${groqKey}",
};
`;

fs.writeFileSync('js/env.js', content, 'utf8');

console.log('✅ js/env.js generated');
if (geminiKey) console.log('   • GEMINI_API_KEY set');
if (groqKey) console.log('   • GROQ_API_KEY set');
if (!geminiKey && !groqKey) console.log('   ⚠️  No API keys found in environment — users must set keys manually in Settings');
